parameters:
    database_driver:   pdo_mysql
    database_host:     mysql51-91.perso
    database_port:     ~
    database_name:     arrasfilfestival
    database_user:     arrasfilfestival
    database_password: w9XcYhbMHMV2

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            fr
    secret:            o9bqwKzBf0HyUrzuEyhnhzqBU

#parameters:
    #database_driver:   pdo_mysql
    #database_host:     localhost
    #database_port:     ~
    #database_name:     arrasfilmfestival
    #database_user:     root
    #database_password: ~

    #mailer_transport:  smtp
    #mailer_host:       127.0.0.1
    #mailer_user:       ~
    #mailer_password:   ~

    #locale:            fr
    #secret:            o9bqwKzBf0HyUrzuEyhnhzqBU
