front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admin

BackOfficeBundle_photo:
    resource: "@BackOfficeBundle/Resources/config/routing/photo.yml"
    prefix:   /admin/photo

BackOfficeBundle_video:
    resource: "@BackOfficeBundle/Resources/config/routing/video.yml"
    prefix:   /admin/video

BackOfficeBundle_podcast:
    resource: "@BackOfficeBundle/Resources/config/routing/podcast.yml"
    prefix:   /admin/podcast

BackOfficeBundle_article:
    resource: "@BackOfficeBundle/Resources/config/routing/article.yml"
    prefix:   /admin/article

BackOfficeBundle_event:
    resource: "@BackOfficeBundle/Resources/config/routing/event.yml"
    prefix:   /admin/event

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

_imagine:
    resource: .
    type:     imagine
