front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admin

BackOfficeBundle_photo:
    resource: "@BackOfficeBundle/Resources/config/routing/photo.yml"
    prefix:   /admin/photo

BackOfficeBundle_video:
    resource: "@BackOfficeBundle/Resources/config/routing/video.yml"
    prefix:   /admin/video

BackOfficeBundle_podcast:
    resource: "@BackOfficeBundle/Resources/config/routing/podcast.yml"
    prefix:   /admin/podcast

BackOfficeBundle_article:
    resource: "@BackOfficeBundle/Resources/config/routing/article.yml"
    prefix:   /admin/article

BackOfficeBundle_event:
    resource: "@BackOfficeBundle/Resources/config/routing/event.yml"
    prefix:   /admin/event

BackOfficeBundle_user:
    resource: "@BackOfficeBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

BackOfficeBundle_team:
    resource: "@BackOfficeBundle/Resources/config/routing/team.yml"
    prefix:   /admin/team

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile