back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /panel

BackOfficeBundle_photo:
    resource: "@BackOfficeBundle/Resources/config/routing/photo.yml"
    prefix:   /panel/photo

BackOfficeBundle_video:
    resource: "@BackOfficeBundle/Resources/config/routing/video.yml"
    prefix:   /panel/video

BackOfficeBundle_podcast:
    resource: "@BackOfficeBundle/Resources/config/routing/podcast.yml"
    prefix:   /panel/podcast

BackOfficeBundle_article:
    resource: "@BackOfficeBundle/Resources/config/routing/article.yml"
    prefix:   /panel/article

BackOfficeBundle_user:
    resource: "@BackOfficeBundle/Resources/config/routing/user.yml"
    prefix:   /panel/user

BackOfficeBundle_team:
    resource: "@BackOfficeBundle/Resources/config/routing/team.yml"
    prefix:   /panel/team
