<?php

namespace ArrasFilmFestival\BackOfficeBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PodcastController__JMSInjector
{
    public static function inject($container) {
        $instance = new \ArrasFilmFestival\BackOfficeBundle\Controller\PodcastController();
        return $instance;
    }
}
