parameters:
#    back_office.example.class: ArrasFilmFestival\BackOfficeBundle\Example

services:
#    back_office.example:
#        class: %back_office.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
