article:
    pattern:  /
    defaults: { _controller: "BackOfficeBundle:Article:index" }

article_show:
    pattern:  /show/{id}
    defaults: { _controller: "BackOfficeBundle:Article:show" }

article_new:
    pattern:  /new
    defaults: { _controller: "BackOfficeBundle:Article:new" }

article_create:
    pattern:  /create
    defaults: { _controller: "BackOfficeBundle:Article:create" }
    requirements: { _method: post }

article_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "BackOfficeBundle:Article:edit" }

article_update:
    pattern:  /update/{id}
    defaults: { _controller: "BackOfficeBundle:Article:update" }
    requirements: { _method: post }

article_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "BackOfficeBundle:Article:delete" }
    requirements: { _method: post }
