photo:
    pattern:  /
    defaults: { _controller: "BackOfficeBundle:Photo:index" }

photo_new:
    pattern:  /new
    defaults: { _controller: "BackOfficeBundle:Photo:new" }

photo_create:
    pattern:  /create
    defaults: { _controller: "BackOfficeBundle:Photo:create" }
    requirements: { _method: post }

photo_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "BackOfficeBundle:Photo:edit" }

photo_update:
    pattern:  /update/{id}
    defaults: { _controller: "BackOfficeBundle:Photo:update" }
    requirements: { _method: post }

photo_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "BackOfficeBundle:Photo:delete" }
    requirements: { _method: post }
