podcast:
    pattern:  /
    defaults: { _controller: "BackOfficeBundle:Podcast:index" }

podcast_new:
    pattern:  /new
    defaults: { _controller: "BackOfficeBundle:Podcast:new" }

podcast_create:
    pattern:  /create
    defaults: { _controller: "BackOfficeBundle:Podcast:create" }
    requirements: { _method: post }

podcast_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "BackOfficeBundle:Podcast:edit" }

podcast_update:
    pattern:  /update/{id}
    defaults: { _controller: "BackOfficeBundle:Podcast:update" }
    requirements: { _method: post }

podcast_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "BackOfficeBundle:Podcast:delete" }
    requirements: { _method: post }
