video:
    pattern:  /
    defaults: { _controller: "BackOfficeBundle:Video:index" }

video_new:
    pattern:  /new
    defaults: { _controller: "BackOfficeBundle:Video:new" }

video_create:
    pattern:  /create
    defaults: { _controller: "BackOfficeBundle:Video:create" }
    requirements: { _method: post }

video_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "BackOfficeBundle:Video:edit" }

video_update:
    pattern:  /update/{id}
    defaults: { _controller: "BackOfficeBundle:Video:update" }
    requirements: { _method: post }

video_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "BackOfficeBundle:Video:delete" }
    requirements: { _method: post }
